### ISSUE TITLE
辞書の修正をユーザが提案できる仕組みを作る

### ISSUE THREAD

**Issue by kitabatake1013** [actlaboratory/ERE#5]
このアドオンでうまく読めない語や、読み方が適切でない（と思われる）語を、ユーザが簡単に報告できるような仕組みを作る。

**Comment by kitabatake1013** [comment]
方法（案）

1. NVDAメニュー→[English Reading Enhancer]→[読み方の修正を提案]を実行する。
1. ダイアログが現れて、以下の情報を指定する。
	* 単語：この機能を実行する前に特定のテキストを範囲選択していれば、それを初期値として入力しておく。
	* 現在の読み方：[単語]の入力値をカナ変換した結果が入る。ユーザは編集できない。
	* 新しい読み方（カタカナ）：読ませたいと思う読み方を指定。
	* コメント（任意）：そう読ませたいと思った経緯などを自由に記述。
	* アドオンのバージョン：自動的に取得して入力。編集できない。
1. [OK]ボタンを押すと、上記内容のGitHub Issueが作られる。
1. アドオン開発者がその内容を確認し、必要に応じて辞書の修正をする。
	* 当該修正を取り込んだ場合は`Completed`としてクローズする。その際、提案された内容を一部変更した場合などは適宜コメントを書いておく。
	* 修正を見送った場合は`Not Planned`としてクローズする。なぜ見送ったかはコメントに書く。

**Comment by yamahubuki** [comment]
issueの作成に際してGitHubのアカウントが必要になるので、そこが課題と思います。
こちらのアカウントで代理投稿するのならばスパム等の対策が必要です。

**Comment by kitabatake1013** [comment]
GitHubのトークンを自分で用意してもらう、という仕組みでも良いかもしれないと思い始めました。
GitHubアカウントが必要など、やや面倒なこともありますが、逆に若干のハードルを設けることによって不適切な書き込みを減らそうという狙いもあります。

**Comment by kitabatake1013** [comment]
「読み間違いの報告」というサブメニューを作って、そこに以下の項目を配置する方針に変更します。

* 読み間違いの報告
* GitHubアクセストークンの設定
* 報告一覧を開く

**Comment by kitabatake1013** [comment]
範囲選択されたテキストを初期値として入力しておく実装は困難なため、断念しました。

報告を送信するダイアログを開く操作に入力ジェスチャーを割り当てられるようにしました。
